// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CreateAnswer(arg1:number,arg2:string):Promise<services.Answer>;

export function CreateComment(arg1:number,arg2:string):Promise<services.Comment>;

export function CreateQuestion(arg1:string,arg2:string):Promise<services.Question>;

export function DeleteAnswer(arg1:number):Promise<void>;

export function DeleteComment(arg1:number):Promise<void>;

export function DeleteQuestion(arg1:number):Promise<void>;

export function DownvoteAnswer(arg1:number):Promise<void>;

export function GetCurrentUser():Promise<services.UserProfile>;

export function GetQuestion(arg1:number):Promise<services.Question>;

export function GetUsername():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function ListAnswers(arg1:number,arg2:number,arg3:number):Promise<Array<services.Answer>>;

export function ListComments(arg1:number,arg2:number,arg3:number):Promise<Array<services.Comment>>;

export function ListQuestions(arg1:number,arg2:number):Promise<Array<services.Question>>;

export function Login(arg1:string,arg2:string):Promise<services.LoginResponse>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<services.RegisterResponse>;

export function SearchQuestions(arg1:string,arg2:number,arg3:number):Promise<Array<services.SearchResult>>;

export function UpdateAnswer(arg1:number,arg2:string):Promise<services.Answer>;

export function UpdateComment(arg1:number,arg2:string):Promise<services.Comment>;

export function UpdateQuestion(arg1:number,arg2:string,arg3:string):Promise<services.Question>;

export function UpvoteAnswer(arg1:number):Promise<void>;
