// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetCurrentUser():Promise<services.UserProfile>;

export function GetUsername():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<services.LoginResponse>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<services.RegisterResponse>;
