// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAnswer(arg1, arg2) {
  return window['go']['main']['App']['CreateAnswer'](arg1, arg2);
}

export function CreateComment(arg1, arg2) {
  return window['go']['main']['App']['CreateComment'](arg1, arg2);
}

export function CreateQuestion(arg1, arg2) {
  return window['go']['main']['App']['CreateQuestion'](arg1, arg2);
}

export function DeleteAnswer(arg1) {
  return window['go']['main']['App']['DeleteAnswer'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['App']['DeleteComment'](arg1);
}

export function DeleteIndexAllQuestions() {
  return window['go']['main']['App']['DeleteIndexAllQuestions']();
}

export function DeleteQuestion(arg1) {
  return window['go']['main']['App']['DeleteQuestion'](arg1);
}

export function DownvoteAnswer(arg1) {
  return window['go']['main']['App']['DownvoteAnswer'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetQuestion(arg1) {
  return window['go']['main']['App']['GetQuestion'](arg1);
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function IndexAllQuestions() {
  return window['go']['main']['App']['IndexAllQuestions']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function ListAnswers(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAnswers'](arg1, arg2, arg3);
}

export function ListComments(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListComments'](arg1, arg2, arg3);
}

export function ListQuestions(arg1, arg2) {
  return window['go']['main']['App']['ListQuestions'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SearchQuestions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchQuestions'](arg1, arg2, arg3);
}

export function UpdateAnswer(arg1, arg2) {
  return window['go']['main']['App']['UpdateAnswer'](arg1, arg2);
}

export function UpdateComment(arg1, arg2) {
  return window['go']['main']['App']['UpdateComment'](arg1, arg2);
}

export function UpdateQuestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateQuestion'](arg1, arg2, arg3);
}

export function UpvoteAnswer(arg1) {
  return window['go']['main']['App']['UpvoteAnswer'](arg1);
}
