// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/proto/search/search.proto

package search

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`    // 搜索关键词
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // 返回结果的最大数量
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // 分页偏移量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionsRequest) Reset() {
	*x = SearchQuestionsRequest{}
	mi := &file_api_proto_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsRequest) ProtoMessage() {}

func (x *SearchQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsRequest.ProtoReflect.Descriptor instead.
func (*SearchQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchQuestionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchQuestionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchQuestionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"` // 搜索结果中的问题列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuestionsResponse) Reset() {
	*x = SearchQuestionsResponse{}
	mi := &file_api_proto_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuestionsResponse) ProtoMessage() {}

func (x *SearchQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuestionsResponse.ProtoReflect.Descriptor instead.
func (*SearchQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_api_proto_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_api_proto_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *Question) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Question) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Question) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Question) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Question) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Question) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_proto_search_search_proto protoreflect.FileDescriptor

const file_api_proto_search_search_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/search/search.proto\x12\x06search\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\x16SearchQuestionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"I\n" +
	"\x17SearchQuestionsResponse\x12.\n" +
	"\tquestions\x18\x01 \x03(\v2\x10.search.QuestionR\tquestions\"\xdd\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x85\x01\n" +
	"\rSearchService\x12t\n" +
	"\x0fSearchQuestions\x12\x1e.search.SearchQuestionsRequest\x1a\x1f.search.SearchQuestionsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/search/questionsB\vZ\t./;searchb\x06proto3"

var (
	file_api_proto_search_search_proto_rawDescOnce sync.Once
	file_api_proto_search_search_proto_rawDescData []byte
)

func file_api_proto_search_search_proto_rawDescGZIP() []byte {
	file_api_proto_search_search_proto_rawDescOnce.Do(func() {
		file_api_proto_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_search_search_proto_rawDesc), len(file_api_proto_search_search_proto_rawDesc)))
	})
	return file_api_proto_search_search_proto_rawDescData
}

var file_api_proto_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_search_search_proto_goTypes = []any{
	(*SearchQuestionsRequest)(nil),  // 0: search.SearchQuestionsRequest
	(*SearchQuestionsResponse)(nil), // 1: search.SearchQuestionsResponse
	(*Question)(nil),                // 2: search.Question
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_api_proto_search_search_proto_depIdxs = []int32{
	2, // 0: search.SearchQuestionsResponse.questions:type_name -> search.Question
	3, // 1: search.Question.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: search.Question.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: search.SearchService.SearchQuestions:input_type -> search.SearchQuestionsRequest
	1, // 4: search.SearchService.SearchQuestions:output_type -> search.SearchQuestionsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_search_search_proto_init() }
func file_api_proto_search_search_proto_init() {
	if File_api_proto_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_search_search_proto_rawDesc), len(file_api_proto_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_search_search_proto_goTypes,
		DependencyIndexes: file_api_proto_search_search_proto_depIdxs,
		MessageInfos:      file_api_proto_search_search_proto_msgTypes,
	}.Build()
	File_api_proto_search_search_proto = out.File
	file_api_proto_search_search_proto_goTypes = nil
	file_api_proto_search_search_proto_depIdxs = nil
}
