// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: search.proto

package search

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_SearchQuestions_FullMethodName         = "/search.SearchService/SearchQuestions"
	SearchService_IndexAllQuestions_FullMethodName       = "/search.SearchService/IndexAllQuestions"
	SearchService_DeleteIndexAllQuestions_FullMethodName = "/search.SearchService/DeleteIndexAllQuestions"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	SearchQuestions(ctx context.Context, in *SearchQuestionsRequest, opts ...grpc.CallOption) (*SearchQuestionsResponse, error)
	// 索引管理方法（仅用于测试/管理）
	IndexAllQuestions(ctx context.Context, in *IndexAllQuestionsRequest, opts ...grpc.CallOption) (*IndexAllQuestionsResponse, error)
	DeleteIndexAllQuestions(ctx context.Context, in *DeleteIndexAllQuestionsRequest, opts ...grpc.CallOption) (*DeleteIndexAllQuestionsResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchQuestions(ctx context.Context, in *SearchQuestionsRequest, opts ...grpc.CallOption) (*SearchQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchQuestionsResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexAllQuestions(ctx context.Context, in *IndexAllQuestionsRequest, opts ...grpc.CallOption) (*IndexAllQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexAllQuestionsResponse)
	err := c.cc.Invoke(ctx, SearchService_IndexAllQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DeleteIndexAllQuestions(ctx context.Context, in *DeleteIndexAllQuestionsRequest, opts ...grpc.CallOption) (*DeleteIndexAllQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIndexAllQuestionsResponse)
	err := c.cc.Invoke(ctx, SearchService_DeleteIndexAllQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
type SearchServiceServer interface {
	SearchQuestions(context.Context, *SearchQuestionsRequest) (*SearchQuestionsResponse, error)
	// 索引管理方法（仅用于测试/管理）
	IndexAllQuestions(context.Context, *IndexAllQuestionsRequest) (*IndexAllQuestionsResponse, error)
	DeleteIndexAllQuestions(context.Context, *DeleteIndexAllQuestionsRequest) (*DeleteIndexAllQuestionsResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) SearchQuestions(context.Context, *SearchQuestionsRequest) (*SearchQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchQuestions not implemented")
}
func (UnimplementedSearchServiceServer) IndexAllQuestions(context.Context, *IndexAllQuestionsRequest) (*IndexAllQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexAllQuestions not implemented")
}
func (UnimplementedSearchServiceServer) DeleteIndexAllQuestions(context.Context, *DeleteIndexAllQuestionsRequest) (*DeleteIndexAllQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIndexAllQuestions not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchQuestions(ctx, req.(*SearchQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexAllQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexAllQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexAllQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexAllQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexAllQuestions(ctx, req.(*IndexAllQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DeleteIndexAllQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexAllQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DeleteIndexAllQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_DeleteIndexAllQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DeleteIndexAllQuestions(ctx, req.(*DeleteIndexAllQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchQuestions",
			Handler:    _SearchService_SearchQuestions_Handler,
		},
		{
			MethodName: "IndexAllQuestions",
			Handler:    _SearchService_IndexAllQuestions_Handler,
		},
		{
			MethodName: "DeleteIndexAllQuestions",
			Handler:    _SearchService_DeleteIndexAllQuestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
