# Docker环境配置文件
# 服务器通用配置
server:
  port: 8080
  mode: "release" # Docker环境使用release模式

# 日志配置
log:
  level: "info"
  format: "json"

# MySQL 数据库配置 (Docker容器内部地址)
mysql:
  host: "mariadb"  # 使用Docker Compose服务名
  port: 3306       # 容器内部端口
  username: "qahub_user"
  password: "12345678"
  dbname: "qahub"
  charset: "utf8mb4"
  parseTime: "True"
  loc: "Local"

# Redis 配置 (Docker容器内部地址)
redis:
  addr: "redis:6379"  # 使用Docker Compose服务名和内部端口
  password: "" 
  db: 0

# Kafka 配置 (供搜索和通知服务使用)
kafka:
  brokers:
    - "kafka:9092"
  topics:
    qa_events: "qa_events" # 用于问答服务和搜索服务之间的事件通信
    notification_events: "notification_events" # 用于通知服务的事件通信

# Elasticsearch 配置 (供搜索服务使用)
elasticsearch:
  username: "qahub_user"
  password: "12345678"
  host: "elasticsearch"
  port: 9200

# MongoDB 配置 (供通知服务使用)
mongodb:
  username: "qahub_admin"
  password: "12345678"
  host: "mongodb"
  port: 27017
  database: "notification_db"

# 服务特有配置
services:
  user_service:
    jwt_secret: "satiu" # 用于生成和验证JWT
    token_expire_hours: 24 # JWT过期时间，单位：小时
    grpc_port: "50051" # gRPC 服务端口
    http_port: "8081" # HTTP 服务端口
    public_methods: # 不需要身份验证的公共API路径
      - "/user.UserService/Register"
      - "/user.UserService/Login"
      - "/grpc.health.v1.Health/Check"
  qa_service:
    grpc_port: "50052"
    http_port: "8082"
    public_methods:
      - "/qa.QAService/ListQuestions"
      - "/qa.QAService/GetQuestion"
      - "/grpc.health.v1.Health/Check"
  search_service:
    grpc_port: "50053"
    http_port: "8083"
    public_methods:
      - "/grpc.health.v1.Health/Check"
  notification_service:
    grpc_port: "50054"
    http_port: "8084"
    public_methods:
      - "/grpc.health.v1.Health/Check"
  gateway:
    port: "8080" # gRPC-Gateway 监听端口
    user_service_endpoint: "user-service:50051" # gRPC 用户服务地址
    qa_service_endpoint: "qa-service:50052" # gRPC 问答服务地址
    search_service_endpoint: "search-service:50053" # gRPC 搜索服务地址
    notification_service_endpoint: "notification-service:50054" # gRPC 通知服务地址