name: Build and Push Docker Images

on:
  workflow_call:  # 允许被其他 workflow 调用
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: "user-service", path: "./cmd/user-service/Dockerfile" }
          - { name: "qa-service", path: "./cmd/qa-service/Dockerfile" }
          - { name: "search-service", path: "./cmd/search-service/Dockerfile" }
          - { name: "notification-service", path: "./cmd/notification-service/Dockerfile" }
    
    name: Build and push ${{ matrix.service.name }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.service.name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service.path }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-${{ matrix.service.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-${{ matrix.service.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
