name: Go Microservices CI/CD

on:
  push:
    branches: [ "chore/setup-ci-cd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      # 为每个模块运行 linter
      - name: Run linter on api
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          working-directory: api

      - name: Run linter on pkg
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          working-directory: pkg

      - name: Run linter on user-service
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          working-directory: cmd/user-service

      - name: Run linter on qa-service
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          working-directory: cmd/qa-service

      - name: Run linter on search-service
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          working-directory: cmd/search-service

      - name: Run linter on notification-service
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          working-directory: cmd/notification-service

      - name: Run linter on wails-client
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          working-directory: cmd/wails-client

      - name: Run unit tests
        run: go test -v -cover work

      # 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 构建并推送 Docker 镜像

      - name: Build and push user-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/user-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-user-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-user-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push qa-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/qa-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-qa-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-qa-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push search-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/search-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-search-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-search-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push notification-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/notification-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-notification-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/qahub-notification-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

