name: Test

on:
  workflow_call:  # 允许被其他 workflow 调用
  workflow_dispatch:  # 允许手动触发

jobs:
  unit-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      # 构建 wails-client 前端
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.9.0'
          cache: 'npm'
          cache-dependency-path: clients/wails-client/frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: clients/wails-client/frontend
        run: npm ci

      - name: Build frontend
        working-directory: clients/wails-client/frontend
        run: npm run build

      - name: Run unit tests
        run: go test -v -cover work

      - name: Generate coverage report
        run: go test -coverprofile=coverage.out work

      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
